config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  authenticated :user do
    root 'categories#index', as: :authenticated_root
  end

  unauthenticated do
    root 'categories#splash', as: :unauthenticated_root
  end

  resources :categories, only: %i[index new show create destroy] do
    resources :purchases, only: %i[index new create destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  has_many :category_purchases
  has_many :purchases, through: :category_purchases

  validates :name, :icon, presence: true

  def total
    purchases.sum(:amount)
  end
end

app/models/category_purchase.rb
class CategoryPurchase < ApplicationRecord
  belongs_to :category
  belongs_to :purchase
end

app/models/purchase.rb
class Purchase < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  has_many :category_purchases
  has_many :categories, through: :category_purchases

  validates :name, presence: true
  validates :amount, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :categories, dependent: :destroy
  has_many :purchases, dependent: :destroy

  attr_accessor :unconfirmed_email

  validates :name, presence: true, length: { minimum: 2, maximum: 50 }, allow_blank: false
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation) }

    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!, except: [:splash]

  def index
    @categories = Category.where(author_id: current_user.id).includes(:purchases)
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(categories_params)
    if @category.save
      redirect_to categories_path, notice: 'Category was successfully created.'
    else
      redirect_to new_category_path, alert: 'Category was not created.'
    end
  end

  def destroy
    @category = Category.find(params[:id])
    if @category.destroy
      redirect_to categories_path, notice: 'Category was successfully deleted.'
    else
      redirect_to new_category_path, alert: 'Category was not deleted.'
    end
  end

  def splash; end

  private

  def categories_params
    params.require(:category).permit(:name, :icon).merge(author_id: current_user.id)
  end
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  def index
    @category = Category.find(params[:category_id])
    @purchases = @category.purchases
    @purchases = @purchases.sort { |a, b| b.created_at <=> a.created_at }
    @total = @purchases.map(&:amount).sum
  end

  def new
    @purchase = Purchase.new
  end

  def create
    @category = Category.find(params[:category_id])
    @purchase = @category.purchases.new(purchases_params)

    if @purchase.save
      CategoryPurchase.create(category_id: @category.id, purchase_id: @purchase.id)
      redirect_to category_purchases_path(category_id: @category.id), notice: 'Purchase was successfully created.'
    else
      redirect_to new_category_purchase_path(category_id: @category.id), alert: 'Purchase was not created.'
      puts @purchase.errors.full_messages
    end
  end

  def destroy
    @category = Category.find(params[:category_id])
    @purchase = @category.purchases.find(params[:id])

    if @purchase.destroy
      redirect_to category_purchases_path(category_id: @category.id), notice: 'Purchase was successfully deleted.'
    else
      redirect_to category_purchases_path(category_id: @category.id), alert: 'Purchase was not deleted.'
    end
  end

  private

  def purchases_params
    params.require(:purchase).permit(:name, :amount).merge(author_id: current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def icon(name)
    content_tag(:i, '', class: name.to_s)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/views/categories/index.html.erb
<%= render 'shared/header', title: "categories", back: false %>

<% if @categories.empty? %>
    <section>
        <div class="intro">
            <h3>Getting started?</h3>
            <p>TrackBudget is a simple app to track your budget. You can add categories to see how much you spent for that category by clicking <span>Add Category</span> button.</p>
            <p>When you click the category after you added, you can see the total purchases for that category and if you don't have any purchases yet, you can add purchase items by clicking <span>Add Purchase</span> button.</p>
            <span>Let's start by adding your first category.</span>
            <i class="fa-regular fa-hand-point-down"></i>
        </div>
    </section>
<% else %>
    <section>
        <ul>
            <% @categories.each do |category| %>
                <%= link_to category_purchases_path(category.id), class: 'categoryLinks' do %>
                    <li class="category">
                        <span><%= category.icon %></span>
                        <span><%= category.name %></span>
                        <span><%= number_to_currency(category.total) %></span>
                    </li>
                <% end %>
            <% end %>
        </ul>
    </section>
<% end %>

<div class="btn">
    <%= link_to "Add Category", new_category_path %>
</div>

app/views/categories/new.html.erb
<%= render 'shared/header', title: "add category", back: categories_path %>

<%= form_with model: @category do |f| %>
    <article>
        <div>
            <%= f.text_field :name, placeholder: "Category name: ", required: true %>
        </div>

        <% options = [  ["🍔 Foods", "🍔"],
                        ["🍷 Drinks", "🍷"],
                        ["☕ Coffee", "☕"],
                        ["🛒 Groceries", "🛒"],
                        ["🚌 Tranportation", "🚌"],
                        ["🐕 Pets", "🐕"],
                        ["🎬 Entertainment", "🎬"],
                        ["📚 Books", "📚"],
                        ["💻 Tech Accessories", "💻"],
                        ["👓 Glasses", "👓"],
                        ["⌚ Watch", "⌚"],
                        ["👔 Men Clothing", "👔"],
                        ["👗 Women Clothing", "👗"],
                        ["👖 Jeans", "👖"],
                        ["👟 Shoes", "👟"],
                        ["👠 High Heels", "👠"],
                        ["👙 Bikini", "👙"],
                        ["🎁 Gift", "🎁"],
                        ["💊 Medicine", "💊"],
                        ["💡 Electric Bill", "💡"],
                        ["💄 Cosmetics", "💄"],
                        ["🧾 Others", "🧾"],
                    ] %>

        <div>
            <%= f.select :icon, options_for_select(options, selected: @category.icon), {prompt: "Select an icon: " } %>
        </div>

    </article>
    <div class="btn">
        <%= f.submit "Create Category" %>
    </div>
<% end %>

app/views/categories/splash.html.erb
<div class="splash">
    <%= image_tag('TrackBudget logo.png', alt: 'Logo', class: 'logo' ) %>
    <div>
        <%= link_to "LOG IN", new_user_session_path, class: 'login' %>
        <%= link_to "SIGN UP", new_user_registration_path, class: 'signup' %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TrackBudget</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag 'custom', "data-turbo-track": "reload" %>
  </head>

  <body>
      <%= render 'shared/menu' %>
      <main class='main'>
        <%= yield %>
      </main>
  </body>
</html>

app/views/purchases/index.html.erb
<%= render 'shared/header', title: "Purchases", back: categories_path %>

<% if @purchases.empty? %>
    <section>
        <div class="purchase-category">
            <span><%= @category.icon %></span>
            <span><%= @category.name %></span>
            <%= button_to icon('fa-solid fa-trash'), category_path(@category), method: :delete, class: 'delBtn' %>
        </div>
        <h2>No purchase found for this category.</h2>
    </section>
<% else %>
    <section>
        <div class="purchase-category">
            <span><%= @category.icon %></span>
            <span><%= @category.name %></span>
            <%= button_to icon('fa-solid fa-trash'), category_path(@category), method: :delete, class: 'delBtn' %>
        </div>
        <ul class="purchase-ul">
            <% @purchases.each do |purchase| %>
                <li class="purchase">
                    <span><%= purchase.name %></span>
                    <span><%= number_to_currency(purchase.amount) %></span>
                    <span class="date">
                        <i class="fa-solid fa-calendar-days"></i>
                        <%= purchase.created_at.strftime('%d-%m-%Y') %>
                    </span>
                    <span class="purchase-del"><%= button_to icon('fa-solid fa-trash-can'), category_purchase_path(@category, purchase), method: :delete, class: 'delBtn' %> </span>
                </li>
            <% end %>
        </ul>
        <div class="total-amount">
            <span>Total amount: </span>
            <span><%= number_to_currency(@total) %></span>
        </div>
    </section>
<% end %>

<div class="btn">
    <%= link_to "Add Purchase", new_category_purchase_path(@category.id) %>
</div>

app/views/purchases/new.html.erb
<%= render 'shared/header', title: "add purchase", back: category_purchases_path %>

<%= form_with model: @purchase, url: category_purchases_path do |f| %>
    <article>
        <div>
            <%= f.text_field :name, placeholder: "Purchase item name: ", required: true %>
        </div>
        <div>
            <%= f.number_field :amount, placeholder: 'Amount in USD: ', required: true, value: nil %>
        </div>
    </article>
    <div class="btn">
        <%= f.submit "Create Purchase" %>
    </div>
<% end %>

app/views/shared/_flash.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/shared/_header.html.erb
<header>
  <% if back %>
    <%= link_to icon('fa-solid fa-chevron-left'), back %>
  <% else %>
    <div class="hamburger">
      <span class="line"></span>
      <span class="line"></span>
      <span class="line"></span>
    </div>
  <% end %>
  <%= title.upcase %>
  <% if title == "Log In" %>
    <%= link_to icon('fa-solid fa-user-plus'), new_user_registration_path %>
  <% elsif title == "Sign Up" %>
    <%= link_to "Log In", new_user_session_path, class: 'login' %>
  <% else %>
    <i class="fa-solid fa-right-from-bracket"></i>
  <% end %>
</header>

<%= render 'shared/flash' %>
<%= render 'shared/popup' %>

app/views/shared/_menu.html.erb
<% if user_signed_in? %>
<nav class="sideMenu">
  <div class="userInfo">
    <i class="fa-solid fa-circle-user"></i>
    <p><%= current_user.name %></p>
  </div>
  <ul>
    <li>
      <i class="fa-solid fa-cog"></i>
      <%= link_to "Acount Settings" %>
    </li>
    <li>
      <i class="fa-solid fa-code"></i>
      <%= link_to "Source Code", "https://github.com/Rhaegar121/Track-Budget" %>
    </li>
    <li>
      <i class="fa-brands fa-github"></i>
      <%= link_to "Author Profile", "https://github.com/Rhaegar121" %>
    </li>
    <li>
      <i class="fa-solid fa-sign-out"></i>
      <%= button_to "Log out", destroy_user_session_path, method: :delete %>
    </li>
  </ul>
</nav>
<% end %>

app/views/shared/_popup.html.erb
<div class="popup">
    <p>Log out of your account?</p>
    <div class="popupBtn">
        <%= button_to "Confirm", destroy_user_session_path, method: :delete, class: "confirm" %>
        <button class="cancel">Cancel</button>
    </div>
</div>